---
- name: "TEST: Tideways needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ tideways_extension_path }}"
    - "{{ tideways_archive }}"
    - "{{ tideways_output_dir }}"
  register: tideways
  failed_when: tideways.stat.exists == false

- name: "TEST: Tideways should use the latest stable release"
  shell: php -c {{ php_ini }} -i | grep 'tideways' | grep -o '{{ tideways_stable_release }}' || echo 'update'
  register: tideways_version_check
  changed_when: tideways_version_check.stdout == "update"
  failed_when: tideways_version_check.stdout == "update"

- name: "TEST: Tideways should be configured in php.ini"
  shell: grep -o "{{ tideways_extension_name }}" {{ php_ini }} || echo "absent"
  register: tideways_phpini
  changed_when: tideways_phpini == "absent"
  failed_when: tideways_phpini == "absent"

- name: "TEST: The Tideways output directory should be writable"
  stat:
    path: "{{ tideways_output_dir }}"
  register: writable_tideways

- name: "TEST: The Tideways output directory should be writable"
  fail:
    msg: "The Tideways output directory isn't writable"
  when: writable_tideways.stat.mode != "0777"
