#!/usr/bin/env bash

run_app_dev() {
  # Comma-separated sitenames are split into single values for drucker to
  # get a list of sites to switch to development mode.
  for SITE in ${SITENAME//,/ }; do
    app_dev
  done
  exit 0
}

run_app_prod() {
  # Comma-separated sitenames are split into single values for drucker to
  # get a list of sites to switch to production mode.
  for SITE in ${SITENAME//,/ }; do
    app_prod
  done
  exit 0
}

run_app_drupal() {
  # Comma-separated sitenames are split into single values for drucker to
  # get a list of sites to create.
  for SITE in ${SITENAME//,/ }; do
    app_drupal
  done
  exit 0
}

run_app_import() {
  # Comma-separated sitenames are split into single values for drucker to
  # get a list of sites to import.
  for SITE in ${SITENAME//,/ }; do
    app_import
  done
  exit 0
}

reinstall_sites() {
  # Comma-separated sitenames are split into single values for drucker to
  # get a list of sites to reinstall.
  for SITE in ${SITENAME//,/ }; do
    drupal_reinstall
  done
  exit 0
}

run_app_blt() {
  # Comma-separated builds are split into single values for drucker to
  # get a list of BLT builds to create.
  for SITE in ${SITENAME//,/ }; do
    app_blt
  done
  exit 0
}

run_app_lightning() {
  # Comma-separated sitenames are split into single values for drucker to
  # get a list of Lightning sites to create.
  for SITE in ${SITENAME//,/ }; do
    app_lightning
  done
  exit 0
}

run_app_reservoir() {
  # Comma-separated sitenames are split into single values for drucker to
  # get a list of Reservoir sites to create.
  for SITE in ${SITENAME//,/ }; do
    app_reservoir
  done
  exit 0
}
