#!/usr/bin/env bash

validation() {
  if [[ -z ${SITENAME} ]]; then
    echo -e "\n${RED}You need to pass a sitename.${COLOR_ENDING}\n"
  elif [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
    echo -e "\n${RED}You cannot use only digits.${COLOR_ENDING}\n"
  fi
}

usage() {
  return_version
cat <<EOF

${ORANGE_HELP}Usage:${COLOR_ENDING_HELP}
  drucker [command] [site,...] [git_tag]

  The [site,...] argument is only valid for the following commands:
    app:[drupal,lightning,reservoir,blt]
    app:[delete,import,dev,prod]

  The [git_tag] argument is only valid for the app:drupal command.

 ${ORANGE_HELP}containers${COLOR_ENDING_HELP}
  ${GREEN_HELP}containers:health${COLOR_ENDING_HELP}   Runs a service healthcheck
  ${GREEN_HELP}containers:start${COLOR_ENDING_HELP}    Starts all drucker containers
  ${GREEN_HELP}containers:stop${COLOR_ENDING_HELP}     Stops all drucker containers
  ${GREEN_HELP}containers:restart${COLOR_ENDING_HELP}  Restarts all drucker containers

 ${ORANGE_HELP}app${COLOR_ENDING_HELP}
  ${GREEN_HELP}app:drupal${COLOR_ENDING_HELP}          Spins up a ready-to-use Drupal install
  ${GREEN_HELP}app:lightning${COLOR_ENDING_HELP}       Spins up a ready-to-use Lightning install
  ${GREEN_HELP}app:reservoir${COLOR_ENDING_HELP}       Spins up a ready-to-use Reservoir install
  ${GREEN_HELP}app:blt${COLOR_ENDING_HELP}             Spins up a ready-to-use BLT build
  ${GREEN_HELP}app:delete${COLOR_ENDING_HELP}          Deletes an arbitrary docroot
  ${GREEN_HELP}app:import${COLOR_ENDING_HELP}          Imports an app from the web container's import directory
  ${GREEN_HELP}app:dev${COLOR_ENDING_HELP}             Prepare app for development work with no caching and helper modules enabled.
  ${GREEN_HELP}app:prod${COLOR_ENDING_HELP}            Opinionated setup with all known performance best practices enabled.

 ${ORANGE_HELP}util${COLOR_ENDING_HELP}
  ${GREEN_HELP}php:[version]${COLOR_ENDING_HELP}       Sets the PHP version to 7.1 or 7.2
  ${GREEN_HELP}version${COLOR_ENDING_HELP}             Returns the drucker version
  ${GREEN_HELP}tests${COLOR_ENDING_HELP}               Runs the Ansible test suite
  ${GREEN_HELP}help${COLOR_ENDING_HELP}                Displays valid drucker commands and their use
EOF
exit 0
}
