#!/usr/bin/env python3

# from sys import version_info
import docker
import colorful

def docker_version():
    client = docker.APIClient(base_url='unix://var/run/docker.sock')
    version = client.version()

    for key in version:
        print(version[key,value])
        # print(key)
    # print(version)
    print(colorful.red('You need to install Docker before running this script.'))

docker_version()
# check_software_requirements() {
#   if [[ -z $(docker --version) ]]; then
