#!/usr/bin/env bash

set_local_ssh_path() {
  if [[ $(grep 'key_path' ${DIR}/config) ]]; then
    export DEFAULT_SSH_PATH="$HOME/.ssh/id_rsa.pub"
    read -p "Enter path to SSH public key [${DEFAULT_SSH_PATH}]: " PUBKEY
    PUBKEY=${PUBKEY:-$DEFAULT_SSH_PATH}

    sed -i "s#key_path#${PUBKEY}#g" ${DIR}/config
  else
    READ_PUBKEY_VAR_LINE=$(sed -n 3p ${DIR}/config | tr -d '"')
    export PUBKEY=${READ_PUBKEY_VAR_LINE:18}
  fi
}

set_local_html_path() {
  if [[ $(grep 'html_path' ${DIR}/config) ]]; then
    export DEFAULT_HOST_HTML_PATH="/var/www/html"

    read -p "Where should we store drucker sites locally? [${DEFAULT_HOST_HTML_PATH}]: " HOST_HTML_PATH
    HOST_HTML_PATH=${HOST_HTML_PATH:-$DEFAULT_HOST_HTML_PATH}

    sed -i "s#html_path#${HOST_HTML_PATH}#g" ${DIR}/config
  else
    READ_HTML_VAR_LINE=$(sed -n 4p ${DIR}/config | tr -d '"')
    export HOST_HTML_PATH=${READ_HTML_VAR_LINE:23}
  fi
}

set_local_db_path() {
  if [[ $(grep 'db_path' ${DIR}/config) ]]; then
    export DEFAULT_HOST_DB_PATH="/var/lib/mysql"

    read -p "Where should we store database backups locally? [${DEFAULT_HOST_DB_PATH}]: " HOST_DB_PATH
    HOST_DB_PATH=${HOST_DB_PATH:-$DEFAULT_HOST_DB_PATH}

    sed -i "s#db_path#${HOST_DB_PATH}#g" ${DIR}/config
  else
    READ_DB_VAR_LINE=$(sed -n 5p ${DIR}/config | tr -d '"')
    export HOST_DB_PATH=${READ_DB_VAR_LINE:21}
  fi
}

load_container_files() {
  CONTAINER_DIR="containers"
  CONTAINER_FILES="variables requirements init ssh orchestration base reverse_proxy web db search"

  for FILES in ${CONTAINER_FILES} ; do
    source "${DIR}/${CONTAINER_DIR}/${FILES}"
  done
}

drucker_usage() {
  echo "Usage: drucker {--version|--dev|--prod|--create [sitename] [git_tag]|--import [sitename]|--reinstall|--composer [sitename]|--delete [sitename]|--tests}"
  exit 0
}

drucker_argument() {
  if [[ -n "${OPTION}" ]] && \
       [[ "${OPTION}" != "--version" ]] && \
       [[ "${OPTION}" != "--dev" ]] && \
       [[ "${OPTION}" != "--prod" ]] && \
       [[ "${OPTION}" != "--create" ]] && \
       [[ "${OPTION}" != "--import" ]] && \
       [[ "${OPTION}" != "--reinstall" ]] && \
       [[ "${OPTION}" != "--composer" ]] && \
       [[ "${OPTION}" != "--delete" ]] && \
       [[ "${OPTION}" != "--tests" ]] && \
       [[ "${OPTION}" != "--help" ]]; then
    drucker_usage
  else
    case "$OPTION" in
      --version)
      DRUCKER_VERSION_CHECK=$(grep "DRUCKER_VERSION" ${DIR}/containers/variables | awk '{print $2}' | grep -oP 'DRUCKER_VERSION="\K[^"]+')
      latest_commit=$(cd ${DIR} && git rev-parse --short HEAD)

      if [[ ${DRUCKER_VERSION_CHECK} == 'dev' ]]; then
        echo ${DRUCKER_VERSION_CHECK}:${latest_commit}
        exit 0
      else
        echo ${DRUCKER_VERSION_CHECK}
        exit 0
     fi
      ;;
      --dev)
      if [[ "${OPTION}" == "--dev" ]] && [[ ! -z ${SITENAME} ]]; then
        drucker_usage
      else
        drupal_dev_mode
        exit 0
      fi
      ;;
      --prod)
      if [[ "${OPTION}" == "--prod" ]] && [[ ! -z ${SITENAME} ]]; then
        drucker_usage
      else
        drupal_prod_mode
        exit 0
      fi
      ;;
      --create)
      if [[ "${OPTION}" == "--create" ]] && [[ -z ${SITENAME} ]]; then
        drucker_usage
      else
        create_site
        exit 0
      fi
      ;;
      --import)
      if [[ "${OPTION}" == "--import" ]] && [[ -z ${SITENAME} ]]; then
        drucker_usage
      else
        import_site
        exit 0
      fi
      ;;
      --reinstall)
      if [[ "${OPTION}" == "--reinstall" ]] && [[ ! -z ${SITENAME} ]]; then
        drucker_usage
      else
        reinstall_drupal
        exit 0
      fi
      ;;
      --composer)
      if [[ "${OPTION}" == "--composer" ]] && [[ -z ${SITENAME} ]]; then
        drucker_usage
      else
        drupal_composer
        exit 0
      fi
      ;;
      --delete)
      if [[ "${OPTION}" == "--delete" ]] && [[ -z ${SITENAME} ]]; then
        drucker_usage
      else
        delete_site
        exit 0
      fi
      ;;
      --tests)
      if [[ "${OPTION}" == "--tests" ]] && [[ ! -z ${SITENAME} ]]; then
        drucker_usage
        exit 0
      else
        run_tests
        exit 0
      fi
      ;;
      --help)
cat <<EOF
--version             Returns the drucker version.
--dev                 Prepare drucker for development work with no caching and helper modules enabled.
                      WARNING: when running automated tests, 'twig_debug' should be set to FALSE.

--prod                Opinionated setup with all known performance best practices enabled.

--create [sitename]   Creates an arbitrary docroot, vHost and corresponding database.

--import [sitename]   Imports the database, files and codebase from the web container's import directory.

--reinstall           Deletes the existing drucker codebase and database and reinstalls from the latest dev tarball.

--composer [sitename] Installs Drupal from a composer.json file

--delete [sitename]   Deletes an arbitrary docroot, vHost and corresponding database.

--tests               Runs the Ansible test suite.
EOF
      exit 0
      ;;
    esac
  fi
}
