#!/usr/bin/env bash

load_function_files() {
  FUNCTION_DIR="functions"
  FUNCTION_FILES="containers_management helpers arguments"

  for FUNCTION_FILE in ${FUNCTION_FILES} ; do
    source "${DIR}/${FUNCTION_DIR}/${FUNCTION_FILE}"
  done
}

load_container_files() {
  CONTAINER_DIR="containers"
  CONTAINER_FILES="variables orchestration web"

  for CONTAINER_FILE in ${CONTAINER_FILES} ; do
    source "${DIR}/${CONTAINER_DIR}/${CONTAINER_FILE}"
  done
}

drucker_argument() {
  if [[ -n "${COMMAND}" ]] && \
       [[ "${COMMAND}" != "containers:health" ]] && \
       [[ "${COMMAND}" != "containers:start" ]] && \
       [[ "${COMMAND}" != "containers:stop" ]] && \
       [[ "${COMMAND}" != "containers:restart" ]] && \
       [[ "${COMMAND}" != "app:list" ]] && \
       [[ "${COMMAND}" != "app:drupal" ]] && \
       [[ "${COMMAND}" != "app:lightning" ]] && \
       [[ "${COMMAND}" != "app:reservoir" ]] && \
       [[ "${COMMAND}" != "app:blt" ]] && \
       [[ "${COMMAND}" != "app:delete" ]] && \
       [[ "${COMMAND}" != "app:import" ]] && \
       [[ "${COMMAND}" != "app:dev" ]] && \
       [[ "${COMMAND}" != "app:prod" ]] && \
       [[ "${COMMAND}" != "php:7.1" ]] && \
       [[ "${COMMAND}" != "php:7.2" ]] && \
       [[ "${COMMAND}" != "version" ]] && \
       [[ "${COMMAND}" != "tests" ]] && \
       [[ "${COMMAND}" != "help" ]]; then
    usage
  else
    case "$COMMAND" in
      containers:health)
        run_healthcheck
      ;;
      containers:start)
      if [[ "${COMMAND}" == "containers:start" ]]; then
        start_containers
      fi
      ;;
      containers:stop)
      if [[ "${COMMAND}" == "containers:stop" ]]; then
        stop_containers
        exit 0
      fi
      ;;
      containers:restart)
      if [[ "${COMMAND}" == "containers:restart" ]]; then
        restart_containers
      fi
      ;;
      app:list)
      if [[ "${COMMAND}" == "app:list" ]]; then
        run_app_list
      fi
      ;;
      app:drupal)
      if [[ "${COMMAND}" == "app:drupal" ]] && [[ -z ${SITENAME} ]] || [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
        validation
        usage
      else
        check_containers_status
        run_app_drupal
      fi
      ;;
      app:lightning)
      # See validation() for details.
      if [[ "${COMMAND}" == "app:lightning" ]] && [[ -z ${SITENAME} ]] || [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
        validation
        usage
      else
        check_containers_status
        run_app_lightning
      fi
      ;;
      app:reservoir)
      # See validation() for details.
      if [[ "${COMMAND}" == "app:reservoir" ]] && [[ -z ${SITENAME} ]] || [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
        validation
        usage
      else
        check_containers_status
        run_app_reservoir
      fi
      ;;
      app:blt)
      if [[ "${COMMAND}" == "app:blt" ]] && [[ -z ${SITENAME} ]] || [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
        validation
        usage
      else
        check_containers_status
        run_app_blt
      fi
      ;;
      app:delete)
      if [[ "${COMMAND}" == "app:delete" ]] && [[ -z ${SITENAME} ]]; then
        usage
      else
        check_containers_status
        run_app_delete
      fi
      ;;
      app:import)
      if [[ "${COMMAND}" == "app:import" ]] && [[ -z ${SITENAME} ]] || [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
        validation
        usage
      else
        check_containers_status
        run_app_import
      fi
      ;;
      app:dev)
      if [[ "${COMMAND}" == "app:dev" ]] && [[ -z ${SITENAME} ]] || [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
        usage
      else
        check_containers_status
        run_app_dev
      fi
      ;;
      app:prod)
      if [[ "${COMMAND}" == "app:prod" ]] && [[ -z ${SITENAME} ]] || [[ ! ${SITENAME} =~ [^[:digit:]] ]]; then
        usage
      else
        check_containers_status
        run_app_prod
      fi
      ;;
      php:7.1)
      if [[ "${COMMAND}" == "php:7.1" ]]; then
        check_containers_status
        set_previous_php_version
        exit 0
      fi
      ;;
      php:7.2)
      if [[ "${COMMAND}" == "php:7.2" ]]; then
        check_containers_status
        set_default_php_version
        exit 0
      fi
      ;;
      version)
      return_version
      exit 0
      ;;
      tests)
      if [[ "${COMMAND}" == "tests" ]] && [[ ! -z ${SITENAME} ]]; then
        usage
        exit 0
      else
        check_containers_status
        run_tests
        exit 0
      fi
      ;;
      help)
      usage
      exit 0
      ;;
    esac
  fi
}
