#!/usr/bin/env bash

# Colors
export GREEN="\033[0;32m"
export RED="\033[0;31m"
export BLUE="\033[94m"
export COLOR_ENDING="\033[0m"

export USER="drucker"

# Networking
export NETWORK="drucker"
export SUBNET="203.0.113.0/24"
export GATEWAY="203.0.113.254"
export BASE_CONTAINER_IP="203.0.113.99"
export REVERSE_PROXY_IP="203.0.113.20"
export WEB_IP="203.0.113.2"

export BASE_IMAGE="debian:latest"
export DRUCKER_INIT_IMAGE="drucker:init"
export DRUCKER_BASE_IMAGE="drucker:base"
export BASE_CONTAINER="drucker_base"
export WEB_CONTAINER="drucker_web"
export REVERSE_PROXY_CONTAINER="drucker_reverse_proxy"
