---
- hosts: drucker_edge
  become: yes

  gather_facts: yes
  vars_files:
    - ../vars.yml
  handlers:
    - import_tasks: ../handlers.yml
  tasks:
    - import_tasks: ../plays/common/mirror-deploy.yml
    - import_tasks: ../plays/common/apt-update.yml
    - import_tasks: ../plays/edge/varnish.yml
    - import_tasks: ../plays/edge/nginx.yml
