---
- hosts: drucker_reverse_proxy
  become: yes

  gather_facts: yes
  vars_files:
    - ../vars.yml
  handlers:
    - import_tasks: ../handlers.yml
  tasks:
    - import_tasks: ../plays/common/mirror-deploy.yml
    - import_tasks: ../plays/common/apt-update.yml
    - import_tasks: ../plays/proxy/varnish.yml
    - import_tasks: ../plays/proxy/nginx.yml
