---
- name: "DEV: Make sure default site has correct permissions"
  file:
    path: "{{ drupal_docroot }}/{{ default_site }}"
    state: directory
    mode: 02755
    owner: "{{ user }}"
    group: "{{ apache_user }}"

- name: "DEV: Check if settings.local.php file exists"
  stat:
    path: "{{ deployed_settings_local_php }}"
  register: settings_local
  ignore_errors: True

- name: "DEV: Create settings.local.php file"
  command: cp {{ settings_local_php_template }} {{ deployed_settings_local_php }}
  become: yes
  become_user: "{{ user }}"
  when: settings_local.stat.exists == false

- name: "DEV: Check if cache bins have been disabled"
  shell: grep -o "\$settings\['cache'\]\['bins'\]" {{ deployed_settings_local_php }} || echo "absent"
  register: cache_bins
  changed_when: cache_bins.stdout == "absent"

- name: "DEV: Disable cache bins"
  replace:
    dest: "{{ deployed_settings_local_php }}"
    regexp: '^(.*)# \$settings\[''cache''\]\[''bins''\](.*)$'
    replace: '\1$settings[''cache''][''bins'']\2'
  when: settings_local.stat.exists == false or cache_bins.stdout == 'absent'

- name: "DEV: Enable settings.local.php"
  blockinfile:
    dest: "{{ deployed_settings_php }}"
    block: |
      if (file_exists(__DIR__ . '/settings.local.php')) {
        include __DIR__ . '/settings.local.php';
      }

    insertafter: EOF
    marker: "# {mark} MANAGED SETTINGS.LOCAL.PHP BLOCK"

- name: "DEV: Check if services.yml exists"
  stat:
    path: "{{ deployed_services_yml }}"
  register: deployed_services_yml_dev
  ignore_errors: True

- name: "DEV: Create services.yml file"
  command: cp {{ services_yml_template }} {{ deployed_services_yml }}
  when: deployed_services_yml_dev.stat.exists == false

- name: "DEV: Turn on Twig debugging"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    debug: false(.*)$'
    replace: '\1    debug: true\2'
  register: turn_on_twig_debugging

- name: "DEV: Turn on Twig auto_reload"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    auto_reload: null(.*)$'
    replace: '\1    auto_reload: true\2'

- name: "DEV: Turn off Twig caching"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    cache: true(.*)$'
    replace: '\1    cache: false\2'

- name: "DEV: Enable the Testing module"
  command: drush --root={{ drupal_root }} pm-enable simpletest

- name: "DEV: Delete composer.lock file"
  file:
    path: "{{ drupal_composer_lock }}"
    state: absent
    force: yes

- name: "DEV: Deploy composer.json dev template"
  copy:
    src: "{{ composer_json_dev_template_file }}"
    dest: "{{ drupal_composer_json }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"

# We're using the shell command here, because using the composer command leaves us
# with missing vendor dependencies, for some reason.
- name: "DEV: Install require-dev vendor dependencies (this can take a while)"
  shell: composer install
  args:
    chdir: "{{ drupal_root }}"
  become: yes
  become_user: "{{ user }}"

- name: "DEV: Check if phpstan.neon exists"
  stat:
    path: "{{ phpstan_neon }}"
  register: phpstan
  ignore_errors: True

- name: "DEV: Deploy phpstan.neon"
  copy:
    src: "{{ phpstan_source_file }}"
    dest: "{{ drupal_root }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ apache_user }}"
  when: phpstan.stat.exists == false

- name: "DEV: Rebuild Drupal cache"
  command: drush --root={{ drupal_root }} cache-rebuild
  when: turn_on_twig_debugging.changed

- name: "DEV: Check the Zend assertions status"
  shell: grep "^zend.assertions = -1" "{{ default_php_ini }}" || echo "on"
  register: zend_assertions_enable
  changed_when: zend_assertions_enable.stdout != "on"

- name: "DEV: Turn on Zend assertions"
  replace:
    dest: "{{ default_php_ini }}"
    regexp: '^(.*)zend.assertions = -1(.*)$'
    replace: '\1zend.assertions = 1\2'
  when: zend_assertions_enable.stdout != "on"

- name: "DEV: Display all errors"
  replace:
    dest: "{{ default_php_ini }}"
    regexp: '^(.*)display_errors = Off(.*)$'
    replace: '\1display_errors = On\2'
  notify: Restart Apache
