---
- name: "PROD: Disable settings.local.php"
  blockinfile:
    dest: "{{ deployed_settings_php }}"
    block: |
      if (file_exists(__DIR__ . '/settings.local.php')) {
        include __DIR__ . '/settings.local.php';
      }

    state: absent
    marker: "# {mark} MANAGED SETTINGS.LOCAL.PHP BLOCK"

- name: "PROD: Check if services.yml exists"
  stat:
    path: "{{ deployed_services_yml }}"
  register: deployed_services_yml_prod
  ignore_errors: True

- name: "PROD: Turn off Twig debugging"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    debug: true(.*)$'
    replace: '\1    debug: false\2'
  register: turn_off_twig_debugging
  when: deployed_services_yml_prod.stat.exists == true

- name: "PROD: Turn off Twig auto_reload"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    auto_reload: true(.*)$'
    replace: '\1    auto_reload: null\2'
  when: deployed_services_yml_prod.stat.exists == true

- name: "PROD: Turn on Twig caching"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    cache: false(.*)$'
    replace: '\1    cache: true\2'
  when: deployed_services_yml_prod.stat.exists == true

- name: "PROD: Check if the Testing module is installed"
  shell: drush --root={{ drupal_root }} pm-list --type=module --status=enabled | grep simpletest | awk '{print $4}'
  register: testing_module_check

- name: "PROD: Uninstall the Testing module"
  command: drush --root={{ drupal_root }} pm-uninstall -y simpletest
  when: testing_module_check.stdout == "Enabled"

- name: "PROD: Delete composer.lock file"
  file:
    path: "{{ drupal_composer_lock }}"
    state: absent
    force: yes

- name: "PROD: Deploy composer.json template"
  copy:
    src: "{{ composer_json_template_file }}"
    dest: "{{ drupal_composer_json }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"

# We're using the shell command here, because using the composer command leaves us
# with missing vendor dependencies, for some reason.
- name: "PROD: Remove require-dev vendor dependencies (this can take a while)"
  shell: composer install
  args:
    chdir: "{{ drupal_root }}"
  become: yes
  become_user: "{{ user }}"

- name: "PROD: Check if phpstan.neon exists"
  stat:
    path: "{{ phpstan_neon }}"
  register: phpstan
  ignore_errors: True

- name: "PROD: Delete phpstan.neon"
  file:
    path: "{{ phpstan_neon }}"
    state: absent
  when: phpstan.stat.exists == true

- name: "PROD: Rebuild Drupal cache"
  command: drush --root={{ drupal_root }} cache-rebuild
  when: turn_off_twig_debugging.changed

- name: "PROD: Check the Zend assertions status"
  shell: grep "^zend.assertions = 1" "{{ default_php_ini }}" || echo "off"
  register: zend_assertions_disable
  changed_when: zend_assertions_disable.stdout != "off"

- name: "PROD: Turn off Zend assertions"
  replace:
    dest: "{{ default_php_ini }}"
    regexp: '^(.*)zend.assertions = 1(.*)$'
    replace: '\1zend.assertions = -1\2'
  when: zend_assertions_disable.stdout != "off"

- name: "PROD: Prevent errors from showing up on screen"
  replace:
    dest: "{{ default_php_ini }}"
    regexp: '^(.*)display_errors = On(.*)$'
    replace: '\1display_errors = Off\2'
  notify: Restart Apache
