#!/usr/bin/env bash

INIT_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${INIT_IMAGE}")
DISTRO_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${DISTRO_IMAGE}")
BASE_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${BASE_IMAGE}")

check_requirements() {
  if [[ -z $(docker --version) ]]; then
    echo "${RED}You need to install Docker before running this script.${COLOR_ENDING}"
    exit 0
  fi

  if [[ -z $(ansible --version) ]]; then
    echo "${RED}You need to install Ansible before running this script.${COLOR_ENDING}"
    exit 0
  fi
}

# Prepare for static IP addresses.
create_custom_bridge_network() {
  if [[ $(docker network ls \
      | awk '{print $2}' \
      | grep "${NETWORK}") ]]; then
    echo -e "${GREEN}Custom ${NETWORK} bridge network already exists.${COLOR_ENDING}"
  else
    echo -e "${BLUE}Creating custom ${NETWORK} bridge network with ID:${COLOR_ENDING}"
    docker network create --subnet "${SUBNET}" --gateway "${GATEWAY}" "${NETWORK}"
  fi
}

update_distro_image() {
  docker images \
  | awk '{print $1":"$2}' \
  | grep "${DISTRO_IMAGE}" \
  | xargs -L1 docker pull
}

pull_base_image_from_docker_hub() {
  if [[ ${DISTRO_IMAGE_EXISTS} ]] && [[ ! ${BASE_IMAGE_EXISTS} ]]; then
    echo -e "${GREEN}${DISTRO_IMAGE} image already exists.${COLOR_ENDING}"
    echo -e "${BLUE}Check if ${DISTRO_IMAGE} can be updated...${COLOR_ENDING}"
      update_distro_image
  elif [[ ! ${DISTRO_IMAGE_EXISTS} ]]; then
    echo -e "${BLUE}Pulling ${DISTRO_IMAGE} image from Docker Hub...${COLOR_ENDING}"
    docker pull "${DISTRO_IMAGE}"
  fi
}

build_init_image() {
  if [[ ${INIT_IMAGE_EXISTS} ]]; then
    echo -e "${GREEN}${INIT_IMAGE} image already exists.${COLOR_ENDING}"
  else
    if [[ ! ${BASE_IMAGE_EXISTS} ]]; then
      echo -e "${BLUE}Building ${INIT_IMAGE} image from Dockerfile...${COLOR_ENDING}"
      # Make sure the Docker build context doesn't get in the way.
      cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd
      docker build -t "${INIT_IMAGE}" .
    fi
  fi
}
