#!/usr/bin/env bash

run_base_container_orchestration() {
  echo -e "${BLUE}Running ${BASE_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i orchestration/hosts orchestration/base.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER}"
}

run_reverse_proxy_orchestration() {
  echo -e "${BLUE}Running ${REVERSE_PROXY_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i orchestration/hosts orchestration/reverse_proxy.yml --user="${USER}"  --extra-vars "ansible_sudo_pass=${USER}"
}

run_web_container_orchestration() {
  echo -e "${BLUE}Running ${WEB_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i orchestration/hosts orchestration/web.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER}"
}
