#!/usr/bin/env bash

run_base_container_orchestration() {
  echo -e "${BLUE}Running ${BASE_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/base.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER}"
}

run_reverse_proxy_container_orchestration() {
  echo -e "${BLUE}Running ${REVERSE_PROXY_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/reverse_proxy.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER}"
}

run_web_container_orchestration() {
  echo -e "${BLUE}Running ${WEB_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  if [[ -n "$OPTION" ]]; then
    case "$OPTION" in
      --dev)
      ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/web.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER} dev=Y prod=N reinstall=N import=N"
      ;;
      --prod)
      ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/web.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER} prod=Y dev=N reinstall=N import=N"
      ;;
      --reinstall)
      ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/web.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER} reinstall=Y dev=N prod=N import=N"
      ;;
      --import)
      ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/web.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER} import=Y dev=N prod=N reinstall=N sitename=${SITENAME}"
      ;;
    esac
  else
    ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/web.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER} dev=N prod=N reinstall=N import=N"
  fi
}

run_db_container_orchestration() {
  echo -e "${BLUE}Running ${DB_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/db.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER}"
}

run_gluster_setup_container_orchestration() {
  echo -e "${BLUE}Running GlusterFS orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/gluster-setup.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER}"
}

run_web2_container_orchestration() {
  echo -e "${BLUE}Running ${WEB_CONTAINER} orchestration on the container...${COLOR_ENDING}"

  ansible-playbook -i "${DIR}"/orchestration/hosts "${DIR}"/orchestration/web2.yml --user="${USER}" --extra-vars "ansible_sudo_pass=${USER}"

  run_gluster_setup_container_orchestration
}
