#!/usr/bin/env bash

# Get the current path to the ansible.cfg override.
CONTAINERS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export ANSIBLE_CONFIG="${CONTAINERS_DIR}/ansible.cfg"

SOLR_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${SOLR_IMAGE}")
CUSTOM_SOLR_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${CUSTOM_SOLR_IMAGE}")
SEARCH_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${SEARCH_IMAGE}")
SEARCH_CONTAINER_STARTED=$(docker ps | grep -o "${SEARCH_CONTAINER}")

create_search_container_from_base_image() {
  echo -e "${BLUE}Spinning up ${SEARCH_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${SEARCH_CONTAINER}" -it \
  -h "${SEARCH_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${SEARCH_IP}" \
  -d -p "${HOST_SEARCH_PORT}":"${SEARCH_PORT}" \
  "${BASE_IMAGE}" bash

  configure_search_container_ssh_access
  run_search_container_orchestration
}

create_search_container_from_search_image() {
  echo -e "${BLUE}Spinning up ${SEARCH_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${SEARCH_CONTAINER}" -it \
  -h "${SEARCH_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${SEARCH_IP}" \
  -d -p "${HOST_SEARCH_PORT}":"${SEARCH_PORT}" \
  "${SEARCH_IMAGE}" bash

  configure_search_container_ssh_access
  run_search_container_orchestration
}

create_search_image_from_search_container() {
  echo -e "${BLUE}Committing ${SEARCH_IMAGE} image from ${SEARCH_CONTAINER} container...${COLOR_ENDING}"

  docker commit -m "${SEARCH_CONTAINER} on $(date +"%Y-%m-%d")" "${SEARCH_CONTAINER}" "${SEARCH_IMAGE}"

  echo -e "${BLUE}Deleting initial container...${COLOR_ENDING}"
  docker rm -f "${SEARCH_CONTAINER}"
  create_search_container_from_search_image
}

start_search_container() {
  docker start "${SEARCH_CONTAINER}" > /dev/null 2>&1
}

provision_search_container() {
  if [[ ${SEARCH_CONTAINER_EXISTS} ]]; then
    echo -e "${GREEN}${SEARCH_CONTAINER} container already exists.${COLOR_ENDING}"

    if [[ ! ${SEARCH_CONTAINER_STARTED} ]]; then
      echo -e "${BLUE}Starting ${SEARCH_CONTAINER} container...${COLOR_ENDING}"
      start_search_container
      run_search_container_orchestration
    else
      run_search_container_orchestration
    fi
  else
    if [[ ${SEARCH_IMAGE_EXISTS} ]]; then
      echo -e "${GREEN}${SEARCH_IMAGE} custom image already exists.${COLOR_ENDING}"
      create_search_container_from_search_image
    else
      create_search_container_from_base_image
      create_search_image_from_search_container
    fi
  fi
}
