#!/usr/bin/env bash

# Colors
export GREEN="\033[0;32m"
export GREEN_HELP=$(printf '\033[0;32m')
export RED="\033[0;31m"
export BLUE="\033[94m"
export ORANGE="\033[38;5;178m"
export ORANGE_HELP=$(printf '\033[38;5;178m')
export COLOR_ENDING="\033[0m"
export COLOR_ENDING_HELP=$(printf '\033[0m')

export DRUCKER_VERSION="dev"

# SSH
export RSA_DRUCKER_WEB="/tmp/id_rsa_drucker_web"
export RSA_KEY_DEPLOYED="/tmp/rsa_key_deployed"

# Search
export SEARCH_USER="solr"
export SEARCH_CORE="${USER}"

# Volume mappings
export CONTAINER_DB_PATH="/var/lib/mysql"
export CONTAINER_HTML_PATH="/var/www/html"

# Networking
export NETWORK="${USER}"
export SUBNET="203.0.113.0/24"
export GATEWAY="203.0.113.254"

# Images
export SOLR_IMAGE="solr:latest"
export CUSTOM_SOLR_IMAGE="${USER}:solr"
export SEARCH_IMAGE="${USER}:search"
export MIRROR_IMAGE="${USER}:mirror"
export EDGE_IMAGE="${USER}:EDGE"
export WEB_IMAGE="${USER}:web"
export DB_IMAGE="${USER}:db"

# Containers
WEB_CONTAINER_EXISTS=$(docker ps -a | grep -o "${WEB_CONTAINER}")
export WEB_CONTAINER_EXISTS
DB_CONTAINER_EXISTS=$(docker ps -a | grep -o "${DB_CONTAINER}")
export DB_CONTAINER_EXISTS
export EDGE_CONTAINER_EXISTS
EDGE_CONTAINER_EXISTS=$(docker ps -a | grep -o "${EDGE_CONTAINER}")
SEARCH_CONTAINER_EXISTS=$(docker ps -a | grep -o "${SEARCH_CONTAINER}")
export SEARCH_CONTAINER_EXISTS

# Services
export WEB_SERVICES="apache2 mysql"
export EDGE_SERVICES="nginx varnish"
export DEFAULT_PHP="7.2"
export PREVIOUS_PHP="7.1"

# Git
export GIT_EXECUTABLE="/usr/bin/git"
export DRUPAL_REPO="/var/www/repo/drupal"
export DRUPAL_VERSION="8.5.x"

# Misc
export MYSQL_DIR_OWNERSHIP="mysql"
export CONTAINER_IMPORT_PATH="/var/www/html/import"
