#!/usr/bin/env bash

# Colors
export GREEN="\033[0;32m"
export RED="\033[0;31m"
export BLUE="\033[94m"
export COLOR_ENDING="\033[0m"

export USER="drucker"
export TLD="local"

export DEFAULT="$HOME/.ssh/id_rsa.pub"

# Networking
export NETWORK="drucker"
export SUBNET="203.0.113.0/24"
export GATEWAY="203.0.113.254"

# IPs
export BASE_CONTAINER_IP="203.0.113.99"
export REVERSE_PROXY_IP="203.0.113.20"
export WEB_IP="203.0.113.2"
export GLUSTER_IP="203.0.113.30"

# Ports
export HOST_REVERSE_PROXY_PORT="81"
export REVERSE_PROXY_PORT="80"
export HOST_WEB_PORT="8180"
export WEB_PORT="8080"
export HOST_WEB2_PORT="8181"
export WEB2_PORT="8080"
export HOST_TCP_GLUSTER_DAEMON_WEB="24005"
export TCP_GLUSTER_DAEMON_WEB="24007"
export HOST_TCP_GLUSTER_DAEMON_WEB2="24006"
export TCP_GLUSTER_DAEMON_WEB2="24008"
export HOST_TCP_GLUSTER_BRICK_WEB="49150"
export TCP_GLUSTER_BRICK_WEB="49152"
export HOST_TCP_GLUSTER_BRICK_WEB2="49151"
export TCP_GLUSTER_BRICK_WEB2="49153"
export HOST_TCP_PORT_MAPPER_WEB="2047"
export TCP_PORT_MAPPER_WEB="2049"
export HOST_TCP_PORT_MAPPER_WEB2="2048"
export TCP_PORT_MAPPER_WEB2="2050"

# Hostnames
export REVERSE_PROXY_HOSTNAME="proxy.${TLD}"
export WEB_HOSTNAME="web.${TLD}"
export GLUSTER_HOSTNAME="gluster.${TLD}"

# Images
export DISTRO_IMAGE="debian:latest"
export INIT_IMAGE="drucker:init"
export BASE_IMAGE="drucker:base"
export REVERSE_PROXY_IMAGE="drucker:reverse_proxy"
export WEB_IMAGE="drucker:web"
export GLUSTER_IMAGE="drucker:gluster"

# Containers
export BASE_CONTAINER="drucker_base"
export WEB_CONTAINER="drucker_web"
export REVERSE_PROXY_CONTAINER="drucker_reverse_proxy"
export GLUSTER_CONTAINER="drucker_gluster"

# Services
export WEB_SERVICES="apache2 mysql glusterfs-server"
export REVERSE_PROXY_SERVICES="nginx varnish"
