#!/usr/bin/env bash

# Colors
export GREEN="\033[0;32m"
export GREEN_HELP=$(printf '\033[0;32m')
export RED="\033[0;31m"
export BLUE="\033[94m"
export ORANGE="\033[38;5;178m"
export ORANGE_HELP=$(printf '\033[38;5;178m')
export COLOR_ENDING="\033[0m"
export COLOR_ENDING_HELP=$(printf '\033[0m')

export DRUCKER_VERSION="dev"
export USER="drucker"
export TLD="local"

# SSH
export RSA_DRUCKER_WEB="/tmp/id_rsa_drucker_web"
export RSA_KEY_DEPLOYED="/tmp/rsa_key_deployed"

# Search
export SEARCH_USER="solr"
export SEARCH_CORE="${USER}"

# Volume mappings
export CONTAINER_DB_PATH="/var/lib/mysql"
export CONTAINER_HTML_PATH="/var/www/html"

# Networking
export NETWORK="${USER}"
export SUBNET="203.0.113.0/24"
export GATEWAY="203.0.113.254"

# IPs
export BASE_CONTAINER_IP="203.0.113.99"
export MIRROR_IP="203.0.113.50"
export REVERSE_PROXY_IP="203.0.113.2"
export WEB_IP="203.0.113.10"
export DB_IP="203.0.113.12"
export SEARCH_IP="203.0.113.13"

# Ports
export SSH_PORT="22"
export HOST_REVERSE_PROXY_PORT="81"
export MIRROR_PORT="3142"
export REVERSE_PROXY_PORT="80"
export HOST_WEB_PORT="8180"
export HOST_DB_PORT="3307"
export HOST_SEARCH_PORT="8984"
export HOST_SEARCH_SSH_PORT="2222"
export WEB_PORT="8080"
export DB_PORT="3306"
export SEARCH_PORT="8983"
export HOST_TCP_PORT_MAPPER_WEB="2047"
export TCP_PORT_MAPPER_WEB="2049"
export HOST_TCP_PORT_MAPPER_DB="2051"
export TCP_PORT_MAPPER_DB="2052"

# Hostnames
export MIRROR_HOSTNAME="mirror.${TLD}"
export REVERSE_PROXY_HOSTNAME="proxy.${TLD}"
export DRUCKER_HOSTNAME="${USER}.${TLD}"
export DB_HOSTNAME="db.${TLD}"
export SEARCH_HOSTNAME="search.${TLD}"

# Images
export DISTRO_IMAGE="debian:stretch"
export SOLR_IMAGE="solr:latest"
export CUSTOM_SOLR_IMAGE="${USER}:solr"
export SEARCH_IMAGE="${USER}:search"
export INIT_IMAGE="${USER}:init"
export BASE_IMAGE="${USER}:base"
export MIRROR_IMAGE="${USER}:mirror"
export REVERSE_PROXY_IMAGE="${USER}:reverse_proxy"
export WEB_IMAGE="${USER}:web"
export DB_IMAGE="${USER}:db"

# Containers
export BASE_CONTAINER="${USER}_base"
export WEB_CONTAINER="${USER}_web"
WEB_CONTAINER_EXISTS=$(docker ps -a | grep -o "${WEB_CONTAINER}")
export WEB_CONTAINER_EXISTS
export DB_CONTAINER="${USER}_db"
DB_CONTAINER_EXISTS=$(docker ps -a | grep -o "${DB_CONTAINER}")
export DB_CONTAINER_EXISTS
export MIRROR_CONTAINER="${USER}_mirror"
export MIRROR_CONTAINER_EXISTS
MIRROR_CONTAINER_EXISTS=$(docker ps -a | grep -o "${MIRROR_CONTAINER}")
export REVERSE_PROXY_CONTAINER="${USER}_reverse_proxy"
export REVERSE_PROXY_CONTAINER_EXISTS
REVERSE_PROXY_CONTAINER_EXISTS=$(docker ps -a | grep -o "${REVERSE_PROXY_CONTAINER}")
export SEARCH_CONTAINER="${USER}_search"
SEARCH_CONTAINER_EXISTS=$(docker ps -a | grep -o "${SEARCH_CONTAINER}")
export SEARCH_CONTAINER_EXISTS

# Services
export WEB_SERVICES="apache2 mysql"
export REVERSE_PROXY_SERVICES="nginx varnish"
export DEFAULT_PHP="7.2"
export PREVIOUS_PHP="7.1"

# Git
export GIT_EXECUTABLE="/usr/bin/git"
export DRUPAL_REPO="/var/www/repo/drupal"
export DRUPAL_VERSION="8.5.x"
