#!/usr/bin/env bash

WEB_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${WEB_IMAGE}")
WEB_CONTAINER_STARTED=$(docker ps | grep -o "${WEB_CONTAINER}")

create_web_container_from_base_image() {
  echo -e "${BLUE}Spinning up ${WEB_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${WEB_CONTAINER}" -it \
  -h "${DRUCKER_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${WEB_IP}" \
  -d -p "${HOST_WEB_PORT}":"${WEB_PORT}" \
  -p "${HOST_TCP_GLUSTER_DAEMON_WEB}":"${TCP_GLUSTER_DAEMON_WEB}" \
  -p "${HOST_TCP_GLUSTER_BRICK_WEB}":"${TCP_GLUSTER_BRICK_WEB}" \
  -p "${HOST_TCP_PORT_MAPPER_WEB}":"${TCP_PORT_MAPPER_WEB}" \
  -v "${HOST_HTML_PATH}":"${CONTAINER_HTML_PATH}" \
  --volumes-from "${DB_CONTAINER}" \
  "${BASE_IMAGE}" bash

  configure_web_container_ssh_access
  run_web_container_orchestration
}

create_web_container_from_web_image() {
  echo -e "${BLUE}Spinning up ${WEB_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${WEB_CONTAINER}" -it \
  -h "${DRUCKER_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${WEB_IP}" \
  -d -p "${HOST_WEB_PORT}":"${WEB_PORT}" \
  -p "${HOST_TCP_GLUSTER_DAEMON_WEB}":"${TCP_GLUSTER_DAEMON_WEB}" \
  -p "${HOST_TCP_GLUSTER_BRICK_WEB}":"${TCP_GLUSTER_BRICK_WEB}" \
  -p "${HOST_TCP_PORT_MAPPER_WEB}":"${TCP_PORT_MAPPER_WEB}" \
  -v "${HOST_HTML_PATH}":"${CONTAINER_HTML_PATH}" \
  --volumes-from "${DB_CONTAINER}" \
  "${WEB_IMAGE}" bash

  configure_web_container_ssh_access
  run_web_container_orchestration
}

create_web_image_from_web_container() {
  echo -e "${BLUE}Committing ${WEB_IMAGE} image from ${WEB_CONTAINER} container...${COLOR_ENDING}"

  docker commit -m "${WEB_CONTAINER} on $(date +"%Y-%m-%d")" "${WEB_CONTAINER}" "${WEB_IMAGE}"

  echo -e "${BLUE}Deleting initial container...${COLOR_ENDING}"
  docker rm -f "${WEB_CONTAINER}"
  create_web_container_from_web_image
}

start_web_container() {
  docker start "${WEB_CONTAINER}" > /dev/null 2>&1
}

provision_web_container() {
  if [[ ${WEB_CONTAINER_EXISTS} ]]; then
    echo -e "${GREEN}${WEB_CONTAINER} container already exists.${COLOR_ENDING}"

    if [[ ! ${WEB_CONTAINER_STARTED} ]]; then
      echo -e "${BLUE}Starting ${WEB_CONTAINER} container...${COLOR_ENDING}"
      start_web_container
      run_web_container_orchestration
    else
      run_web_container_orchestration
    fi
  else
    if [[ ${WEB_IMAGE_EXISTS} ]]; then
      echo -e "${GREEN}${WEB_IMAGE} custom image already exists.${COLOR_ENDING}"
      create_web_container_from_web_image
    else
      create_web_container_from_base_image
      create_web_image_from_web_container
    fi
  fi
}

allow_web_to_db_ssh_access() {
  if [[ ! -f ${RSA_DRUCKER_WEB} ]]; then
    docker cp "${WEB_CONTAINER}":/home/"${USER}"/.ssh/id_rsa.pub "${RSA_DRUCKER_WEB}"
    KEY=$(cat "${RSA_DRUCKER_WEB}")
    docker exec -u "${USER}" -it "${DB_CONTAINER}" /bin/grep -q "${KEY}" /home/"${USER}"/.ssh/authorized_keys > "${RSA_KEY_DEPLOYED}"

    if [[ ! -s "${RSA_KEY_DEPLOYED}" ]]; then
      docker exec -u "${USER}" -it "${DB_CONTAINER}" bash -c "echo '${KEY}' >> /home/${USER}/.ssh/authorized_keys"
    fi
  else
    docker cp "${WEB_CONTAINER}":/home/"${USER}"/.ssh/id_rsa.pub "${RSA_DRUCKER_WEB}"_check
    KEY_CHECK=$(cat "${RSA_DRUCKER_WEB}"_check)
    docker exec -u "${USER}" -it "${DB_CONTAINER}" /bin/grep -q "${KEY_CHECK}" /home/"${USER}"/.ssh/authorized_keys > "${RSA_KEY_DEPLOYED}"

    if [[ ! -s "${RSA_KEY_DEPLOYED}" ]]; then
      docker exec -u "${USER}" -it "${DB_CONTAINER}" bash -c "echo '${KEY_CHECK}' >> /home/${USER}/.ssh/authorized_keys"
    fi
  fi

}
