#!/usr/bin/env bash

WEB_CONTAINER_EXISTS=$(docker ps -a | grep -o "${WEB_CONTAINER}")
WEB_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${WEB_IMAGE}")
WEB_CONTAINER_STARTED=$(docker ps | grep -o "${WEB_CONTAINER}")

create_web_container_from_web_image() {
  echo -e "${BLUE}Spinning up ${WEB_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${WEB_CONTAINER}" -it \
  -h "${WEB_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${WEB_IP}" \
  -d -p "${WEB_PORT}":"${WEB_PORT}" \
  "${WEB_IMAGE}" bash

  configure_web_container_ssh_access
  run_web_container_orchestration

  docker restart "${WEB_CONTAINER}"
}

create_web_container_from_base_image() {
  echo -e "${BLUE}Spinning up ${WEB_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${WEB_CONTAINER}" -it \
  -h "${WEB_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${WEB_IP}" \
  -d -p "${WEB_PORT}":"${WEB_PORT}" \
  "${BASE_IMAGE}" bash

  configure_web_container_ssh_access
  run_web_container_orchestration
}

create_web_image_from_web_container() {
  echo -e "${BLUE}Committing ${WEB_IMAGE} image from ${WEB_CONTAINER} container...${COLOR_ENDING}"

  docker commit -m "${WEB_CONTAINER} on $(date +"%Y-%m-%d")" "${WEB_CONTAINER}" "${WEB_IMAGE}"
}

start_web_container() {
  docker start "${WEB_CONTAINER}" > /dev/null 2>&1
}

provision_web_container() {
  if [[ ${WEB_CONTAINER_EXISTS} ]]; then
    echo -e "${GREEN}${WEB_CONTAINER} container already exists.${COLOR_ENDING}"

    if [[ ! ${WEB_CONTAINER_STARTED} ]]; then
      echo -e "${BLUE}Starting ${WEB_CONTAINER} container...${COLOR_ENDING}"
      start_web_container
      run_web_container_orchestration
    else
      run_web_container_orchestration
    fi
  else
    if [[ ${WEB_IMAGE_EXISTS} ]]; then
      echo -e "${GREEN}${WEB_IMAGE} custom image already exists.${COLOR_ENDING}"
      create_web_container_from_web_image
    else
      create_web_container_from_base_image
      create_web_image_from_web_container
    fi
  fi
}
