#!/usr/bin/env bash

WEB2_CONTAINER_EXISTS=$(docker ps -a | grep -o "${WEB2_CONTAINER}")
WEB_IMAGE_EXISTS=$(docker images | awk '{print $1":"$2}' | grep "${WEB_IMAGE}")
WEB2_CONTAINER_STARTED=$(docker ps | grep -o "${WEB2_CONTAINER}")

create_web2_container_from_base_image() {
  echo -e "${BLUE}Spinning up ${WEB2_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${WEB2_CONTAINER}" -it \
  -h "${WEB2_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${WEB2_IP}" \
  -d -p "${HOST_WEB2_PORT}":"${WEB2_PORT}" \
  -p ${HOST_TCP_GLUSTER_DAEMON_WEB2}:"${TCP_GLUSTER_DAEMON_WEB2}" \
  -p ${HOST_TCP_GLUSTER_BRICK_WEB2}:"${TCP_GLUSTER_BRICK_WEB2}" \
  -p ${HOST_TCP_PORT_MAPPER_WEB2}:"${TCP_PORT_MAPPER_WEB2}" \
  "${BASE_IMAGE}" bash

  configure_web2_container_ssh_access
  run_web2_container_orchestration
}

create_web2_container_from_web_image() {
  echo -e "${BLUE}Spinning up ${WEB2_CONTAINER} container with ID:${COLOR_ENDING}"

  docker run --privileged=true --name "${WEB2_CONTAINER}" -it \
  -h "${WEB2_HOSTNAME}" \
  --net "${NETWORK}" \
  --ip "${WEB2_IP}" \
  -d -p "${HOST_WEB2_PORT}":"${WEB2_PORT}" \
  -p ${HOST_TCP_GLUSTER_DAEMON_WEB2}:"${TCP_GLUSTER_DAEMON_WEB2}" \
  -p ${HOST_TCP_GLUSTER_BRICK_WEB2}:"${TCP_GLUSTER_BRICK_WEB2}" \
  -p ${HOST_TCP_PORT_MAPPER_WEB2}:"${TCP_PORT_MAPPER_WEB2}" \
  "${WEB_IMAGE}" bash

  configure_web2_container_ssh_access
  run_web2_container_orchestration
}

start_web2_container() {
  docker start "${WEB2_CONTAINER}" > /dev/null 2>&1
}

provision_web2_container() {
  if [[ ${WEB2_CONTAINER_EXISTS} ]]; then
    echo -e "${GREEN}${WEB2_CONTAINER} container already exists.${COLOR_ENDING}"

    if [[ ! ${WEB2_CONTAINER_STARTED} ]]; then
      echo -e "${BLUE}Starting ${WEB2_CONTAINER} container...${COLOR_ENDING}"
      start_web2_container
      run_web2_container_orchestration
    else
      run_web2_container_orchestration

      if [[ $(</dev/tcp/${WEB2_IP}/${TCP_GLUSTER_DAEMON_WEB} && echo Port open) ]]; then
        run_gluster_setup_container_orchestration
      fi
    fi
  else
    if [[ ${WEB_IMAGE_EXISTS} ]]; then
      echo -e "${GREEN}${WEB_IMAGE} custom image already exists.${COLOR_ENDING}"
      create_web2_container_from_web_image
    fi
  fi
}
