---
# Invoked via run_tests() in containers/orchestration.
- hosts: drucker_mirror
  become: yes

  gather_facts: yes
  vars_files:
    - ../vars.yml
  handlers:
    - import_tasks: ../handlers.yml
  tasks:
    - import_tasks: plays/run-mirror-tests.yml
