---
- name: "RESERVOIR: Check if new site exists"
  stat:
    path: "{{ drupal_root }}"
  register: new_site
  ignore_errors: True

- name: "RESERVOIR: Check if new database exists"
  stat:
    path: "{{ db_data }}/{{ sitename }}"
  register: new_db

- name: "RESERVOIR: Install vendor dependencies (this can take a while)"
  composer:
    command: create-project
    arguments: acquia/reservoir-project {{ sitename }} --stability=alpha
    working_dir: "{{ webroot }}"
  become: yes
  become_user: "{{ user }}"

- name: "RESERVOIR: Create config directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 02755
    owner: "{{ user }}"
    group: "{{ apache_user }}"
  with_items:
    - "{{ drupal_root }}/config"
    - "{{ drupal_root }}/{{ default_configuration_dir }}"
  when: new_site.stat.exists == false

- include: ../common/drupal-common.yml

- name: "RESERVOIR: Install Drupal"
  command: drush @{{ sitename }}.{{ tld }} site-install reservoir install_configure_form.update_status_module='array(FALSE,FALSE)' -qy --db-url=mysql://{{ db_creds }}:{{ db_creds }}@{{ db_ip }}:{{ db_port }}/{{ sitename }} --site-name={{ sitename }} --site-mail={{ drupal_creds }}@{{ sitename }}.{{ tld }} --account-name={{ drupal_creds }} --account-pass={{ drupal_creds }} --account-mail={{ drupal_creds }}@{{ sitename }}.{{ tld }}
  become: yes
  become_user: "{{ user }}"
  when: new_aliases.stat.exists == false

- name: "RESERVOIR: Check if phpunit.xml file exists"
  stat:
    path: "{{ drupal_root }}/docroot/core/phpunit.xml"
  register: reservoir_phpunit

- name: "RESERVOIR: Deploy phpunit.xml file"
  copy:
    src: "{{ phpunit_source_file }}"
    dest: "{{ drupal_root }}/docroot/core/"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: reservoir_phpunit.stat.exists == false

- name: "RESERVOIR: Modify phpunit.xml file"
  replace:
    dest: "{{ drupal_root }}/docroot/core/phpunit.xml"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ sitename }}\2'
  when: reservoir_phpunit.stat.exists == false

- name: "RESERVOIR: Make sure we're down one level for the PHPUnit path"
  replace:
    dest: "{{ drupal_root }}/docroot/core/phpunit.xml"
    regexp: '^(.*){{ drupal_root }}(.*)$'
    replace: '\1{{ drupal_root }}/docroot\2'
  when: reservoir_phpunit.stat.exists == false

- name: "RESERVOIR: Check if .gitignore exists"
  stat:
    path: "{{ drupal_root }}/.gitignore"
  register: reservoir_gitignore
  ignore_errors: True

- name: "RESERVOIR: Create .gitignore file"
  copy:
    src: "{{ gitignore_source_file }}"
    dest: "{{ drupal_root }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: reservoir_gitignore.stat.exists == false

- name: "RESERVOIR: Check if Git repository exists"
  stat:
    path: "{{ drupal_root }}/.git"
  register: reservoir_git_repo
  ignore_errors: True

- name: "RESERVOIR: Initialize Git repository"
  shell: git -C {{ drupal_root }} init
  args:
    warn: no
  register: initial_commit
  become: yes
  become_user: "{{ user }}"
  when: reservoir_git_repo.stat.exists == false

- name: "RESERVOIR: Add all new files under version control"
  shell: git -C {{ drupal_root }} add --all . && git -C {{ drupal_root }} commit -m "Initial commit"
  become: yes
  become_user: "{{ user }}"
  when: reservoir_git_repo.stat.exists == false

- name: "RESERVOIR: Make sure files dir ownership is correct"
  file:
    path: "{{ drupal_root }}/{{ default_site }}/files"
    owner: "{{ user }}"
    group: "{{ apache_user }}"
    recurse: yes
  when: new_site.stat.exists == false or new_db.stat.exists == false
